#!/bin/bash

#if [ "x$1" == "x" ]
#then
#  export LAUNCHER_DIR=../
#else
#  export LAUNCHER_DIR=$1
#fi


# Chantis have the following configuration:
# Host = 1
# Sockets per host:   2
# Cores per host:     28
# Threads per host:   56
#
# For chantis, number of host == number of nodes (probably)
# 
# LAUNCHER_PPN = 56 is the maximum number of processes for chanti and
#  will assign each process to each of the threads.
#
# LAUNCHER_SCHED=dynamic requires python 2.7 or above. Use the conda environment py27
export LAUNCHER_DIR=/data2/mhassan/launcher/
export LAUNCHER_JOB_FILE=part2_decoys.sh
export LAUNCHER_SCHED=interleaved
export LAUNCHER_WORKDIR=`pwd`

#export LAUNCHER_NPROCS=600
export LAUNCHER_NHOSTS=1
export LAUNCHER_PPN=3
export LAUNCHER_BIND=1

$LAUNCHER_DIR/paramrun
